apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
  namespace: default
type: Opaque
data:
  mysql-root-password: bXlzcWxwYXNzd29yZA==
  postgres-password: cG9zdGdyZXNwYXNz
  redis-password: cmVkaXNwYXNz
  rabbitmq-password: cmFiYml0bXFwcw==


