name: Terraform Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: Terraform Apply
    runs-on: ubuntu-latest
    
    # Set environment variables for the entire job
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: eu-west-1  # Hard-coded since you're using eu-west-1
    
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.7.0
    
    # Debug: Terraform version
    - name: Terraform Version
      run: terraform version
      # Remove working-directory if files are in root, or adjust path
    
    # Debug: AWS credentials & region
    - name: Debug AWS Environment
      run: |
        echo "AWS Region: $AWS_DEFAULT_REGION"
        aws sts get-caller-identity
    
    # Terraform Init
    - name: Terraform Init
      run: terraform init
      # Remove working-directory if files are in root
    
    # Validate Terraform syntax
    - name: Terraform Validate
      run: terraform validate
    
    # Terraform Plan
    - name: Terraform Plan
      run: terraform plan -out=tfplan
    
    # Debug: show plan output (only for PRs to avoid logs being too long)
    - name: Terraform Plan Output
      if: github.event_name == 'pull_request'
      run: terraform show tfplan
    
    # Terraform Apply (only on main branch)
    - name: Terraform Apply
      if: github.ref == 'refs/heads/main'
      run: terraform apply -auto-approve tfplan
