name: Terraform CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  terraform-check:
    name: Terraform Validation & Planning
    runs-on: ubuntu-latest
    
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: eu-west-1
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.7.0
    
    - name: Terraform Format Check
      run: terraform fmt -check
      working-directory: infrastructure/terraform
    
    - name: Terraform Init
      run: terraform init
      working-directory: infrastructure/terraform
    
    - name: Terraform Validate
      run: terraform validate
      working-directory: infrastructure/terraform
    
    - name: Terraform Plan
      run: terraform plan
      working-directory: infrastructure/terraform
