name: Terraform Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: Terraform Apply
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.7.0

    # Debug: Terraform version
    - name: Terraform Version
      run: terraform version
      working-directory: infrastructure/terraform

    # Validate Terraform syntax
    - name: Terraform Validate
      run: terraform validate
      working-directory: infrastructure/terraform

    # Debug: AWS credentials & region
    - name: Debug AWS Environment
      run: |
        echo "AWS Region: $AWS_DEFAULT_REGION"
        aws sts get-caller-identity
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

    # Terraform Init
    - name: Terraform Init
      run: terraform init
      working-directory: infrastructure/terraform

    # Terraform Plan
    - name: Terraform Plan
      run: terraform plan -out=tfplan
      working-directory: infrastructure/terraform

    # Debug: show plan output
    - name: Terraform Plan Output
      run: terraform show tfplan
      working-directory: infrastructure/terraform

    # Terraform Apply
    - name: Terraform Apply
      if: github.ref == 'refs/heads/main'
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      run: terraform apply -auto-approve tfplan
      working-directory: infrastructure/terraform

